Description: Development environment stack for ratemanager
Resources:
  lambdaRoleC844FDB1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: Lambda role for ratemanager-lambda
      RoleName: ratemanager-lambda-lambda-role-develop
    Metadata:
      aws:cdk:path: ratemanager-lambda-stack-develop/lambdaRole/Resource
  lambdaExecutionAccess82ECF6E2:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: lambdaExecutionAccess
      Roles:
        - Ref: lambdaRoleC844FDB1
    Metadata:
      aws:cdk:path: ratemanager-lambda-stack-develop/lambdaExecutionAccess/Resource
  webhookfunctionfunction827DEA8F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-760389274302-ap-south-1
        S3Key: 8ad527d39078840d8e617845220858d200c5ddbbd99ca45a7bd7c03056e78fb8.zip
      Role:
        Fn::GetAtt:
          - lambdaRoleC844FDB1
          - Arn
      Environment:
        Variables:
          REGION: ap-south-1
          ENV: develop
          GIT_BRANCH: develop
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      FunctionName: ratemanager-lambda-webhook-function-develop
      Handler: index.handler
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 900
    DependsOn:
      - lambdaRoleC844FDB1
    Metadata:
      aws:cdk:path: ratemanager-lambda-stack-develop/webhook-function-function/Resource
      aws:asset:path: C:\Users\shash\Code_Repos\POCS\RateManager\cdk.out\asset.8ad527d39078840d8e617845220858d200c5ddbbd99ca45a7bd7c03056e78fb8
      aws:asset:is-bundled: true
      aws:asset:property: Code
  fnwebhookfunctionloggroupA41DFDB9:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ratemanager-lambda-webhook-function-develop
      RetentionInDays: 30
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ratemanager-lambda-stack-develop/fn-webhook-function-log-group/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/z1Pyw7CIBD8Fu90bWuiZ2uiF2NM/YCGUmxoKZguaAzh3wWqnmZmk3lsCWUO+Yq+MGPdmEnRgrsZykYSTo0TdAJXa8nJ4a4SXrUU7B3lwjyRdGo72ijd8QHhkuBoFTNCK4KbhiJyg7CPEDRUlo3cVBT51woh7G+QukdwZ92fZm0fsefHvScpI8zrherTIo7azox7EtthwPWz2EKxCx8NKEQ2W2XExKFe8AMYviGY7QAAAA==
    Metadata:
      aws:cdk:path: ratemanager-lambda-stack-develop/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

